apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: access-management
  newName: jackhoman/kubeflow-access-management
  newTag: 4b7b118-dirty
namespace: kubeflow-system

resources:
- deployment.yaml
- serviceaccount.yaml
- service.yaml
- role.yaml
- rolebinding.yaml
