---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-management
subjects:
- kind: ServiceAccount
  name: access-management
  namespace: kubeflow-system
