---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-management
rules:
- apiGroups: [kubeflow.org]
  resources:
  - profiles
  - contributors
  - profiles/finalizers
  - profiles/status
  verbs:
  - create
  - update
  - delete
  - patch
  - list
  - watch
  - get