---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-manager
  labels:
    app.kubernetes.io/part-of: kubeflow
    app: profile-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: kubeflow
      app: profile-manager
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/part-of: kubeflow
        app: profile-manager
    spec:
      containers:
      - name: manager
        command:
        - /controller
        image: jackhoman/kubeflow-profile-manager:7e6bfb1-dirty-controller
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 8080
          name: manager-http
          protocol: TCP
      serviceAccountName: profile-manager