---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-manager-istio
  labels:
    rbac.kubeflow.org/aggregate-to-profile-manager: "true"
rules:
  - apiGroups: [security.istio.io]
    resources:
      - authorizationpolicies
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - watch
      - get
