---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-manager
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.kubeflow.org/aggregate-to-profile-manager: "true"
    - matchLabels:
        rbac.kubeflow.org/aggregate-to-kubeflow-edit: "true"
    - matchLabels:
        rbac.kubeflow.org/aggregate-to-kubeflow-admin: "true"
    - matchLabels:
        rbac.kubeflow.org/aggregate-to-kubeflow-view: "true"
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-manager-leader-election
  labels:
    rbac.kubeflow.org/aggregate-to-profile-manager: "true"
rules:
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: [""]
  resources: [configmaps]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources: [configmaps/status]
  verbs:
  - get
  - update
  - patch
- apiGroups: [""]
  resources: [events]
  verbs: [create]