name: tests
on:
  push:
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - run: go mod tidy && git diff --check
      - run: make test
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - run: |
          make docker-build
          make docker-push
          make publish-api > access-management.yaml
          make publish > profile-manager.yaml
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            access-management.yaml
            profile-manager.yaml
